### ISSUE TITLE
Feature request - Allow speed dial to remain expanded when item is tapped

### ISSUE THREAD

**Issue by barbeau** [markormesher/android-fab#14] opened 2017-08-17 21:43 UTC
Great library!

We're using this library to control which map layers are visible on a map.  We currently have it implemented for bikeshare.  

The below screenshots show from left to right:
* Bikes visible and speed dial control closed
* Bikes visible and speed dial control expanded
* Bikes disabled and speed dial control expanded

![image](https://user-images.githubusercontent.com/928045/29434909-e28cd072-8372-11e7-93ed-e19ea4878e4b.png)

The main usability issue we have now is that when the user taps on the bikeshare icon to toggle layer visibility, the control closes and you can't see the color of the control change.  Ideally, we'd like to leave the control expanded and change the color so it's easier to visually associate with the same color markers disappearing and appearing on the map.  So, the user could tap on the expanded "Bikeshare" control multiple times while it's expanded to toggle the layer on and off, without the control closing on each tap.

Would adding an option to allow the control to remain expanded when tapped be something you'd be interested in integrating?  If we find the time to implement this ourselves, would you merge a pull request with this feature?

(FYI, WIP PR that includes this control is at https://github.com/OneBusAway/onebusaway-android/pull/776)

cc @carvalhorr

**Comment by markormesher** [comment] 2017-08-18 07:46
Hi @barbeau and @carvalhorr!

Thank you for this suggestion - I agree, it would be a good addition to the library. As you may have seen in other issues there is a full re-write of this library in progress at the moment, so I'm generally not adding new features. However, this should be quite a small addition, so I will take a look this weekend and see if I can get it released.

**Comment by barbeau** [comment] 2017-08-18 13:07
@markormesher Thanks, that would be awesome!  We plan to push a new beta release next week, and then to production a week or two later (assuming no major issues are found).  It would be great to be able to include this feature.

**Comment by markormesher** [comment] 2017-08-20 18:15
This issue has shown me how long it's been since I touched this project. It turns out that what you want is already implemented and I completed forgot! Quoting the docs for the `onMenuItemClick` (in the README.md):

> Return `true` to close the menu after the click has been handled (the default behaviour) or `false` to leave it open.

The bad news is that to change the icon colour you'd need to call the `rebuildSpeedDialMenu` method, which has a bug causing undesired behaviour if called when the speed-dial menu is still open (#12). The good news is that I've just fixed that in v1.3.3, so you should be all set now!

**Comment by barbeau** [comment] 2017-08-21 00:43
@markormesher That's awesome, thanks!!  We'll check it out.

**Comment by barbeau** [comment] 2017-08-22 19:50
@markormesher This seems to work well for leaving the control open when tapping!  Thanks!

However, we're hitting an issue with the view that's between the map and speed dial - it blocks any scrolling of the map while the dial is expanded.  Any suggestions for allowing the map to scroll while keeping the speed dial open?  

(Alternately, a solution that immediately collapses the speed dial and passes the touch events to the map to avoid interfering with the user dragging/tapping the map would work too).

If you're curious, the implementation is in https://github.com/carvalhorr/onebusaway-android/blob/adec83406c01fcf6146c0f1240766f2da0f44e2a/onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java, the control is `mLayersFab`.

@carvalhorr is looking at this as well.

**Comment by carvalhorr** [comment] 2017-08-22 19:57
I was wondering if there is a way to disable the cover view? I could set its visibility to GONE 100ms after the speed dial opens, but this is a hack and I could have problems in the future if the library changes.

**Comment by barbeau** [comment] 2017-08-22 20:15
@markormesher Unless there is a better way to do this, would making `FloatingActionButton.setSpeedDialCoverVisible()` a `public` instead of `private` method be a reasonable solution in the library?

**Comment by markormesher** [comment] 2017-08-22 20:34
The trouble with using `setSpeedDialCoverVisible` for your use case is that it controls the animation, so if it was made public and you used it to hide the cover, you might see some stuttering. Would an option to enable/disable the cover entirely work better?

**Comment by barbeau** [comment] 2017-08-22 20:36
>Would an option to enable/disable the cover entirely work better?

Yes, I think so.  That's what @carvalhorr was looking for, and he's been more hands-on than I have with this.

**Comment by markormesher** [comment] 2017-08-22 20:51
Potential: https://github.com/markormesher/android-fab/commit/a2fec492545838494f671badb92606d2b91a29ad

The only problem with this is that the user-expected behaviour of "tap outside the speed dial menu to close it" is removed, because the cover view is what receives those tap events to close the menu.

**Comment by barbeau** [comment] 2017-08-22 20:58
Maybe a better solution is to have the cover close the speed dial on touch event, but pass the touch event to the underlying view?

This would allow the user to immediately drag or tap on the map without interference from the speed dial, and these touch events would close the speed dial.

IMHO, the important thing is to avoid interfering with the use of the underlying map when the user touches it - leaving the speed dial expanded is secondary.  We have another view in our app that behaves similarly - when you tap on the arrival time, it drops down a little view that shows how early/delayed the bus is:

![image](https://user-images.githubusercontent.com/928045/29587142-003f3af6-875b-11e7-8530-97827ca97e37.png)

If you touch the app anywhere outside of that view, it closes and passes that touch event to the view that the user touched.

@carvalhorr Any thoughts on this?

**Comment by carvalhorr** [comment] 2017-08-22 21:02
> Potential: a2fec49

This looks good. 

I don't think it would be a problem with the expected behaviour since by default it works as expected. By adding the possibility to disable the default behaviour you can make the library be used in different use cases.

@barbeau I think the speed dial being open while interacting with the map is interesting. I was able to see the effect of activating one item of the speed dial when I clicked on it (using my hack).

**Comment by barbeau** [comment] 2017-08-22 21:04
@carvalhorr and @markormesher Ok, works for me!

**Comment by markormesher** [comment] 2017-08-22 21:07
I'll go ahead and merge+release that now then.

> Maybe a better solution is to have the cover close the speed dial on touch event, but pass the touch event to the underlying view?

This is definitely worth looking into, but more than I can release right now (10pm for me) and probably out of scope for the current version, as a re-write is in progress. I'm planning for the re-write to be much more customisable, so I'll take this into consideration.

**Comment by carvalhorr** [comment] 2017-08-22 21:12
Thanks @markormesher 

We are in the same timezone. Time to stop for today for me too.

**Comment by markormesher** [comment] 2017-08-22 21:17
Published as v1.3.4 :+1: 

Closing this for now, but open it up if you have any troubles with the update.

**Closed as completed** 2017-08-22 21:18 UTC
Labels: feature request

**Comment by barbeau** [comment] 2017-08-22 21:20
Awesome, thanks @markormesher!  We really appreciate your work on this and quick release (especially with the late night)!

**Comment by barbeau** [comment] 2017-08-22 21:28
>I'm planning for the re-write to be much more customisable, so I'll take this into consideration.

@markormesher Also, if it helps, we have a number of UI utility methods licensed under Apache v2.0 in our `UIUtils` class:
https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/util/UIUtils.java

In particular, [`UIUtils.isTouchInView()`](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/util/UIUtils.java#L1293) may be helpful:

~~~
/**
 * Returns true if the provided touch event was within the provided view
 *
 * @return true if the provided touch event was within the provided view
 */
public static boolean isTouchInView(View view, MotionEvent event) {
	Rect rect = new Rect();
	view.getGlobalVisibleRect(rect);
	return rect.contains((int) event.getRawX(), (int) event.getRawY());
}
~~~

That's what we use, along with `PopupWindow.setTouchInterceptor()`, to hide to delay/early indicator popup in [`ArrivalsListHeader.setupPopup()`](https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListHeader.java#L825).

**Comment by markormesher** [comment] 2017-08-23 08:08
That could definitely be helpful, thank you!
